stages:
  - build

.build-image:
  stage: build
  image: debian:12
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
    - ./ci/prepare-build-host.sh
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - images.tar.gz
  tags:
    - docker

qemu-aarch64:
  extends: .build-image
  script:
    - ./build.sh qemu_aarch64_virt_defconfig

raspberry-pi2:
  extends: .build-image
  script:
    - ./build.sh raspberrypi2_defconfig
