stages:
  - build

.build-image:
  stage: build
  image: debian:12
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
    - ./ci/prepare-build-host.sh
    - ./ci/build.sh
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - images.tar.gz

qemu-aarch64:
  extends: .build-image
  script:
    - ./ci/build.sh qemu_aarch64_virt_uutils_coreutils_defconfig

raspberry-pi2:
  extends: .build-image
  script:
    - ./ci/build.sh raspberrypi2_uutils_coreutils_defconfig
