stages:
  - multicall-images
  - non-multicall-images

.build-image:
  image: alexshcdr/uutils-coreutils-buildroot
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_SHORT_SHA}"
    expire_in: 1 days
    paths:
      - images.tar.gz
  tags:
    - docker

qemu-aarch64-multicall:
  extends: .build-image
  stage: multicall-images
  script:
    - ./build-img.sh qemu_aarch64_virt_defconfig

raspberry-pi3-multicall:
  extends: .build-image
  stage: multicall-images
  script:
    - ./build-img.sh raspberrypi3_defconfig

qemu-aarch64-non-multicall:
  extends: .build-image
  stage: non-multicall-images
  when: manual
  script:
    - ./build-img.sh qemu_aarch64_virt_defconfig non-multicall

raspberry-pi3-non-multicall:
  extends: .build-image
  stage: non-multicall-images
  when: manual
  script:
    - ./build-img.sh raspberrypi3_defconfig non-multicall
